apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: rahmnathan-portfolio
  name: rahmnathan-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rahmnathan-portfolio
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rahmnathan-portfolio
    spec:
      containers:
      - image: {{.Values.localmovies.imageRepository}}/rahmnathan-portfolio:latest
        imagePullPolicy: Always
        name: rahmnathan-portfolio
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: application-config 
          mountPath: /opt/rahmnathan-portfolio/config
          readOnly: true
      dnsConfig:
        nameservers:
         - 8.8.8.8
      volumes:
      - name: application-config
        configMap:
          name: rahmnathan-portfolio
          items:
          - key: bootstrap.properties
            path: bootstrap.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
