apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: rahmnathan-portfolio
  name: rahmnathan-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rahmnathan-portfolio
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rahmnathan-portfolio
    spec:
      containers:
        - image: {{.Values.rahmnathan.imageRepository}}/rahmnathan-portfolio:@project.version@
          imagePullPolicy: Always
          name: rahmnathan-portfolio
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30